name: Build

on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v7
      
      - name: Setup .NET environment
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: "8.x"
          cache: true
          cache-dependency-path: '**/packages.lock.json'
      
      - name: Restore solution
        run: |
          dotnet restore
      
      - name: Build solution
        run: |
          dotnet build -c Release
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: build-artifacts
          path: "./HostFixes/bin/Release/HostFixes.dll"