name: Build

on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0
      
      - name: Setup .NET environment
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.100"
      
      - name: Restore solution
        run: |
          dotnet restore
      
      - name: Build solution
        run: |
          dotnet build -c Release
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: "./HostFixes/bin/Release/netstandard2.1/HostFixes.dll"