name: Publish Mod To TS

on:
    push:
      tags:
        - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Use checkout to publish the files in your repo
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"

      - name: Restore and Build
        run: |
          dotnet restore
          dotnet tool restore
          dotnet build

      - name: Publish to TS
        env:
          # go to settings/secrets/actions -> add new repository secret name it
          # TCLI_AUTH_TOKEN and put a service worker token for your CharlesE2
          # in it. WARNING: Service workers only show up ONCE and are encrypted
          # by github after input so you can never recover it from the TS or GH
          # if you ever need it again. Save the token if you plan to use it on
          # other repositories but treat it like a password, it can be used to
          # publish to your Thunderstore Namespace
          TCLI_AUTH_TOKEN: ${{ secrets.TCLI_AUTH_TOKEN }}
        run: |
          dotnet tcli publish --config-path "./tspublish/thunderstore.toml" --package-version ${{ github.ref_name }}